/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClientSchema extends BaseModel {
  static $columns = ['email', 'id', 'name'] as const
  $columns = ClientSchema.$columns
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
}

export class GatewaySchema extends BaseModel {
  static $columns = ['activeIs', 'id', 'name', 'priority'] as const
  $columns = GatewaySchema.$columns
  @column({ columnName: 'active_is' })
  declare activeIs: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare priority: number
}

export class ProductSchema extends BaseModel {
  static $columns = ['amount', 'id', 'name'] as const
  $columns = ProductSchema.$columns
  @column()
  declare amount: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
}

export class TransactionProductSchema extends BaseModel {
  static $columns = ['id', 'transactionId', 'productId', 'quantity'] as const
  $columns = TransactionProductSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column({ columnName: 'transaction_id' })
  declare transactionId: number
  @column({ columnName: 'product_id' })
  declare productId: number
  @column()
  declare quantity: number
}

export class TransactionSchema extends BaseModel {
  static $columns = ['amount', 'cardLastNumbers', 'clientId', 'externalId', 'gatewayId', 'id', 'status'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare amount: number
  @column({ columnName: 'card_last_numbers' })
  declare cardLastNumbers: string
  @column({ columnName: 'client_id' })
  declare clientId: number
  @column({ columnName: 'external_id' })
  declare externalId: string
  @column({ columnName: 'gateway_id' })
  declare gatewayId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
}

export class UserSchema extends BaseModel {
  static $columns = ['email', 'id', 'password', 'role'] as const
  $columns = UserSchema.$columns
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare role: string | null
}
